#!/bin/bash

set -e

FWPATH="../"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Build for nrf52832 with RX7, TX6, LED8

cd $FWPATH
make clean
make -j8 IS_52832=1 build_args='-DMODULE_BUILTIN=1'
make IS_52832=1 merge_hex
cd $DIR
cp $FWPATH/hex/merged.bin nrf52832_vesc_ble_rx8_tx6_led3.bin
cp $FWPATH/hex/merged.hex nrf52832_vesc_ble_rx8_tx6_led3.hex
# Clean
cd $FWPATH
make clean
cd $DIR

